### ISSUE TITLE
Tablecells scroll behind Section

### ISSUE THREAD

**Issue by ogezue** [iSofTom/STCollapseTableView#11]
Your project is great! Perhaps you can give me a hint how to solve the problem that when using sections with texts the cells scroll behind the sections where they disappear. It is not very pretty that the content of the cells and the sections merge and I would like to solve this.

Do you have an idea how the cells could disappear behind the section without the merging? The sections should always be at the top of all cells.

Cheers ogezue

**Comment by lgamble** [comment]
Not sure if it helps but I changed the tableview style to Grouped rather than the default Plain

**Comment by ogezue** [comment]
Yes, it helped. I also changed the insert animation to UITableViewRowAnimationMiddle. Not perfect, but better than before.
