### ISSUE TITLE
Swift support ?

### ISSUE THREAD

**Issue by Kharauzov** [iSofTom/STCollapseTableView#32]
Hi Thomas ! 
Thanks a lot for this lib. I used it many times already. It is very useful instrument, when you want to customise collapse feature in tableview for your demands.
But, as all new projects are being written at Swift now, it would be cool, if STCollapseTableView has Swift language version.
I am going to rewrite it for latest Swift using your obj-c version.

**Comment by baoluo** [comment]
@Kharauzov Hello, did you convert the files in the end or no ?
It would be nice if you can send me the swift file 😅

**Comment by Kharauzov** [comment]
Hi, @baoluo, unfortunately no. I tried to do this, but failed. As far as I remember, there was something in this pod, that was able to perform only via Objective-C (relating to old api).

**Comment by baoluo** [comment]
Ok thank you very much for your response ! 

Envoyé de mon iPhone

**Comment by Kharauzov** [comment]
@baoluo let me know please, if you managed to convert it to Swift. Cheers

**Comment by baoluo** [comment]
Yes I will, I need to think if I really need it in swift or not, but if I do the conversion I’ll let you know 

Envoyé de mon iPhone

**Comment by Kharauzov** [comment]
For those, who was interested in the Swift version of STCollapseTableView, I've just implemented it.
https://github.com/Kharauzov/CollapseTableView
Closing this issue.
